---
- name: Instalar y configurar Apache
  hosts: servidores_web
  become: true  # Permite ejecutar comandos como sudo

  tasks:
    - name: Actualizar la lista de paquetes
      ansible.legacy.apt:
        update_cache: true
      when: ansible_pkg_mgr == 'apt'  #

    - name: Instalar Apache
      ansible.legacy.apt:
        name: apache2
        state: present  # Asegurarse de que el paquete esté instalado

    - name: Iniciar y habilitar Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true  # Habilitar el inicio

    - name: Copiar archivo de configuración
      ansible.builtin.template:
        src: apache.conf.j2  # Puedes tener
        dest: /etc/apache2/apache2.conf
        mode: 0640
      notify:
        - Reiniciar Apache  # Notificar

  handlers:
    - name: Reiniciar Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
