---
- name: Instalar y configurar Apache
  hosts: servidores_web
  become: true  # Permite ejecutar comandos como sudo

  tasks:
    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'  # Se ejecutará solo en sistemas basados en Debian

    - name: Instalar Apache
      apt:
        name: apache2
        state: present  # Asegurarse de que el paquete esté instalado

    - name: Iniciar y habilitar Apache
      service:
        name: apache2
        state: started
        enabled: yes  # Habilitar el inicio automático al arrancar el sistema

    - name: Copiar archivo de configuración
      template:
        src: apache.conf.j2  # Puedes tener un archivo de plantilla con variables
        dest: /etc/apache2/apache2.conf
      notify:
        - Reiniciar Apache  # Notificar al manejador cuando se copie el archivo de configuración

  handlers:
    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted
