---
- name: Instalar y configurar Apache
  hosts: servidores_web
  become: true  # Permite ejecutar comandos como sudo

  tasks:
    - name: Actualizar la lista de paquetes
      apt:
        update_cache: true
      when: ansible_pkg_mgr == 'apt'  #

    - name: Instalar Apache
      apt:
        name: apache2
        state: present  # Asegurarse de que el paquete esté instalado

    - name: Iniciar y habilitar Apache
      service:
        name: apache2
        state: started
        enabled: true  # Habilitar el inicio 

    - name: Copiar archivo de configuración
      template:
        src: apache.conf.j2  # Puedes tener 
        dest: /etc/apache2/apache2.conf
      notify:
        - Reiniciar Apache  # Notificar

  handlers:
    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted
