---
# Mi inventario de ejemplo
[grupo1]
nodo1 ansible_host=192.168.1.101 ansible_user=usuario ansible_ssh_pass=1234
[grupo2]
nodo3 ansible_host=192.168.1.103 ansible_user=usuario ansible_ssh_pass=1234
[localhost]
127.0.0.1 ansible_connection=local ansible_user=root ansible_become=true
